apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:  
    - name: nginx
      image: nginx
      env: 
        - name: course
          valueFrom:
            configMapKeyRef:
              name: nginx-config #name of the config map you are referring to
              key: course # env.name and config map key name need not to be same
        - name: duration
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: duration
