apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:  #these are replica set labels
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:  #these are used to select POD to create replicas
    matchLabels:
      tier: frontend 
      app: nginx
  template:  #this is POD defination
    metadata: #these labels belongs to POD
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---
kind: Service
apiVersion: v1
metadata: 
  name: nginx
spec:
  selector:
    tier: frontend 
    app: nginx
  ports:
  - name: nginx-svc-ports
    protocol: TCP
    port: 89 #service port
    targetPort: 80 #conainer port
    
